"""Change prompt_text to Text

Revision ID: 09b8f239281e
Revises: dbe375a178f5
Create Date: 2024-11-07 18:07:57.103160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09b8f239281e'
down_revision = 'dbe375a178f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt_text',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
