"""Add start_date and end_date to EmailAccount

Revision ID: 11df9f34c996
Revises: 1588a5c389ff
Create Date: 2024-11-05 16:45:56.479097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11df9f34c996'
down_revision = '1588a5c389ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_entry', mysql.LONGTEXT(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('log_entry')

    # ### end Alembic commands ###
