"""Add start_date and end_date to EmailAccount, add order to AIPrompt

Revision ID: 301142416f21
Revises: 09b8f239281e
Create Date: 2024-11-08 12:35:15.999150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '301142416f21'
down_revision = '09b8f239281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
