"""Rename email_account_id to account_id in Filter model

Revision ID: 566df0bbac0f
Revises: a78aa3fc141e
Create Date: 2024-11-04 18:34:26.445210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '566df0bbac0f'
down_revision = 'a78aa3fc141e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('filter_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'])
        batch_op.drop_column('email_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_account_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('filter_ibfk_2', 'email_account', ['email_account_id'], ['id'])
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
