"""remove job. add order to filters

Revision ID: 6a9a3c61653e
Revises: 9badde469a01
Create Date: 2024-11-05 11:05:43.630279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9a3c61653e'
down_revision = '9badde469a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user_data', schema=None) as batch_op:
    #     batch_op.drop_index('uq_user_account_data')

    op.drop_table('user_data')
    op.drop_table('job')
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_column('order')

    op.create_table('job',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datetime', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('prompt', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('exclusion_words', mysql.VARCHAR(length=2500), nullable=True),
    sa.Column('inclusion_words', mysql.VARCHAR(length=2500), nullable=True),
    sa.Column('processing_status', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='job_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['email_account.id'], name='user_data_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.create_index('uq_user_account_data', ['user_id', 'account_id'], unique=True)

    # ### end Alembic commands ###
