"""Update Email unique constraint to include folder

Revision ID: 7b7999312643
Revises: cf93d3999fd9
Create Date: 2024-11-26 13:07:15.260024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7999312643'
down_revision = 'cf93d3999fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        # batch_op.drop_index('uq_user_account_email')
        batch_op.create_unique_constraint('uq_user_account_email_folder', ['user_id', 'account_id', 'email_id', 'folder'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_account_email_folder', type_='unique')
        batch_op.create_index('uq_user_account_email', ['user_id', 'account_id', 'email_id'], unique=True)

    # ### end Alembic commands ###
