"""Add order column to AIPrompt and other changes

Revision ID: 97b90385c7c4
Revises: 6a9a3c61653e
Create Date: 2024-11-05 12:06:12.905370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97b90385c7c4'
down_revision = '6a9a3c61653e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=False))
        batch_op.alter_column('prompt_text',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.alter_column('filter',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('filter',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('prompt_text',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('action')

    # ### end Alembic commands ###
