"""Remove inclusion_words and exclusion_words from UserData

Revision ID: 9badde469a01
Revises: 566df0bbac0f
Create Date: 2024-11-04 18:42:54.114904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9badde469a01'
down_revision = '566df0bbac0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('inclusion_words')
        batch_op.drop_column('exclusion_words')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclusion_words', mysql.VARCHAR(length=2500), nullable=True))
        batch_op.add_column(sa.Column('inclusion_words', mysql.VARCHAR(length=2500), nullable=True))

    # ### end Alembic commands ###
