"""Add indexes to EmailAddress.email and Email.sender, Email.receivers

Revision ID: cf93d3999fd9
Revises: f2152f6cce81
Create Date: 2024-11-18 19:10:19.857197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf93d3999fd9'
down_revision = 'f2152f6cce81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_index('ix_email_receivers', ['receivers'], mysql_length=255)
        batch_op.create_index('ix_email_sender', ['sender'], unique=False)

    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.create_index('ix_email_address_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.drop_index('ix_email_address_email')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index('ix_email_sender')
        batch_op.drop_index('ix_email_receivers')

    # ### end Alembic commands ###
