"""Add cascade delete to foreign keys

Revision ID: d1e76d5b25d4
Revises: 301142416f21
Create Date: 2024-11-09 13:52:51.748941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e76d5b25d4'
down_revision = '301142416f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.drop_constraint('ai_prompt_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('ai_prompt_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint('email_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('email_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_account', schema=None) as batch_op:
        batch_op.drop_constraint('email_account_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_address_email_account', type_='foreignkey')
        batch_op.drop_constraint('fk_email_address_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_email_address_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_email_address_email_account', 'email_account', ['email_account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_folder', schema=None) as batch_op:
        batch_op.drop_constraint('email_folder_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('email_folder_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_constraint('filter_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('filter_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('result_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('result_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'email_account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('result_ibfk_1', 'email_account', ['account_id'], ['id'])
        batch_op.create_foreign_key('result_ibfk_2', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('filter_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('filter_ibfk_2', 'email_account', ['account_id'], ['id'])

    with op.batch_alter_table('email_folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('email_folder_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('email_folder_ibfk_2', 'email_account', ['account_id'], ['id'])

    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_address_email_account', type_='foreignkey')
        batch_op.drop_constraint('fk_email_address_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_email_address_user', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_email_address_email_account', 'email_account', ['email_account_id'], ['id'])

    with op.batch_alter_table('email_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('email_account_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('email_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('email_ibfk_2', 'email_account', ['account_id'], ['id'])

    with op.batch_alter_table('ai_prompt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ai_prompt_ibfk_2', 'email_account', ['account_id'], ['id'])
        batch_op.create_foreign_key('ai_prompt_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
